### ISSUE TITLE
build-scripts requires a Perl-Critic version not available on SL6

### ISSUE THREAD

**Issue by jouvin** [quattor/maven-tools#131]
Required minimum version is  1.118 when the available version is  1.05... This makes impossible to succeed `00-tqu.t` test when present... (seen in `ncm-lib-blockdevices`).

**Comment by stdweird** [comment]
below missing rpms to be added to the external repo.

they come from http://mirror.city-fan.org/ftp/contrib/yum-repo/ and are signed, but our quattor externals repo has gpgcheck disabled. the nice people of city-fan provide the src rpms, so we could rebuild them and sign them ourself if needed

i'll mail these to @jrha @jouvin and @ned21 so they can be added to the externals repo (and testing can continue in the meantime).

with the rpms in place and https://github.com/quattor/release/pull/281 merged, build_all_repos should be able to do its magic again

```
./noarch
./noarch/el6
./noarch/el6/perl-PPIx-Utilities-1.001000-22.rhel6.noarch.rpm
./noarch/el6/perl-Perl-Critic-1.126-4.rhel6.noarch.rpm
./noarch/el6/perl-PPI-1.220-7.rhel6.noarch.rpm
./noarch/el6/perl-PPIx-Regexp-0.051-1.rhel6.noarch.rpm
./noarch/el5
./noarch/el5/perl-PPI-1.220-7.rhel5.noarch.rpm
./noarch/el5/perl-PPIx-Regexp-0.051-1.rhel5.noarch.rpm
./noarch/el5/perl-Perl-Critic-1.126-4.rhel5.noarch.rpm
./noarch/el5/perl-PPIx-Utilities-1.001000-22.rhel5.noarch.rpm
./x86_64
./x86_64/el5
./x86_64/el5/perl-Class-XSAccessor-1.19-9.rhel5.x86_64.rpm
```

**Comment by jrha** [comment]
I'll add them to the externals repo, but I won't sign them. It would be statement of integrity which I cannot make for external packages.

**Comment by stdweird** [comment]
ok. can we add a short README saying where the rpms came from (and who signed them)? i'd like to credit other peoples work (in this case the city-fan people; because i also tried but failed to make my own recent perl-critic rpms on el5)

**Comment by jrha** [comment]
Sure!

**Comment by stdweird** [comment]
build_all_repos is not succesaful on el6 (was already on el7). el5 still gives issues, but nothing to do with missing rpms.

@jouvin feel free to close this issue

**Comment by jrha** [comment]
not successful or **now** successful?

**Comment by stdweird** [comment]
oops, now succesful

**Comment by jrha** [comment]
I've corrected your comment :smile:
