### ISSUE TITLE
Test::Quattor::ProfileCache::get_config_for_profile does not error if requested profile is not imported via "use Test::Quattor"

### ISSUE THREAD

**Issue by ned21** [quattor/maven-tools#79]
I made a mistake when adding a new PAN file to ncm-spma/src/test/resources. I copied an existing one and failed to update the template line. As a result the compile failed but no error message was  shown in the unit test output, even when running prove -v. The only indication that there was a problem was an error about calling getElement() on an undefined value.

**Comment by stdweird** [comment]
can you run the test (with faulty template) with the `mvn_test` from https://github.com/quattor/quattor.github.com/issues/146#issuecomment-144681288

compiler errors are (well, should be) fatal.

**Comment by ned21** [comment]
hmm.. I seem to be back to square one - the template isn't being compiled. Is there a list of resources to be compiled kept somewhere or does it compile everything that matches *.pan?

**Comment by stdweird** [comment]
@ned21 only templates that are "imported" are compiled. if you have a branch you can push, i can have a look. also, make sure you do a `mvn clean test`, not just `mvn test` (or use `mvn_test` function from above.).

**Comment by ned21** [comment]
By "imported" do you mean this statement does it? ```my $cfg = get_config_for_profile("simple_ng");```

ah, or in fact you mean: ```use Test::Quattor qw(simple simply_ng with_proxy without_spma with_pkgs);```

Thanks for the pointer. :-)

**Comment by stdweird** [comment]
yes, the compilation is done by `use Test::Quattor qw(sometemplate);` by redefining the import in https://github.com/quattor/maven-tools/blob/master/build-scripts/src/main/perl/Test/Quattor.pm#L213

`get_config_for_profile` returns the correct configuration instance from the CCM DB cache

i guess a tutorial is welcome :smile:

**Comment by ned21** [comment]
I confirmed that template errors are shown. I think it would have been useful if get_config_for_profile(foo) could check and error if foo is not imported.
