### ISSUE TITLE
Update Maven plugins

### ISSUE THREAD

**Issue by jouvin** [quattor/maven-tools#83]
Running `mvn versions:display-plugin-updates` reveals that we are running a lot of outdated plugins. would be good to update them after 16.4 release.

**Comment by wdpypere** [comment]
maybe wait until this gets in: https://github.com/mojohaus/rpm-maven-plugin/pull/66.

**Comment by ned21** [comment]
@wdpypere How often does that maven plugin get released? i.e. how long might we have to wait for that feature?

**Comment by wdpypere** [comment]
@ned21 looking at https://github.com/mojohaus/rpm-maven-plugin/releases , there does not seem to be a release cycle defined. a new milestone is defined and I can see 2 PR's merged since last release in February. So to be honest, your guess is as good as mine.

**Comment by wdpypere** [comment]
@ned21 I posted the question to their google group here: https://groups.google.com/forum/#!topic/mojohaus-dev/sXo3mV7JdEA

**Comment by jrha** [comment]
I'm not sure how to go about this, but we could be waiting for the rpm plugin for a while.
@jouvin if you want to open a PR for 17.3 feel free.
