### ISSUE TITLE
RPMs are built with an non-standard group

### ISSUE THREAD

**Issue by jrha** [quattor/maven-tools#91]
We currently have the group set to "quattor", we should probably consider changing the group to something like `Applications/System`, which seems to be the best fit out of the standard groups.

Will remove one more `rpmlint` warning.

As originally discussed in quattor/LC#14.

**Comment by jrha** [comment]
Valid groups to choose from can be found in `/usr/share/doc/rpm-*/GROUPS`, the list has not changed for a long time (since Redhat 9?):

```
Amusements/Games
Amusements/Graphics
Applications/Archiving
Applications/Communications
Applications/Databases
Applications/Editors
Applications/Emulators
Applications/Engineering
Applications/File
Applications/Internet
Applications/Multimedia
Applications/Productivity
Applications/Publishing
Applications/System
Applications/Text
Development/Debuggers
Development/Languages
Development/Libraries
Development/System
Development/Tools
Documentation
System Environment/Base
System Environment/Daemons
System Environment/Kernel
System Environment/Libraries
System Environment/Shells
User Interface/Desktops
User Interface/X
User Interface/X Hardware Support
```

**Comment by jrha** [comment]
I've had a look at which groups some other configuration management tools use for RPMs:
* ansible - `Development/Libraries`
* bcfg2 - `Applications/System`
* cfengine - `System Environment/Base`
* salt - `System Environment/Daemons`
* puppet - `System Environment/Base`

So definitely `System` something...

**Comment by stdweird** [comment]
i vote for `System Environment/Base`, seems most related
